#!/usr/bin/env bash
set -euf -o pipefail

# node_modules/.bin/sanctuary-lint "$@"

scripts/generate-js && git diff --exit-code index.js
scripts/generate-ts && git diff --exit-code index.d.ts
scripts/generate-es && git diff --exit-code index.mjs
